### ISSUE TITLE
🐛 [BUG] Treemap: Conditional color function stays present until full rerender

### ISSUE THREAD

**Issue by stenterstal** [ant-design/ant-design-charts#762]
### 🐛 Bug description
When conditonally using the color function to return a color for the items in the treemap the function keeps being applied even after setting the condition to false.

### 📷 Step to reproduce

1. Initially the chart calculates the colors itself
2. Check "show colored data", color is now calculated by color function that is passed with the config (only when this.state.colored is **true**)
3. Now uncheck "show colored data", all items are shown grey (Fallback of the color function)

### 🏞 Expected result

- Would expect that the chart starts calculating the colors itself again because the color function is only added conditionally (when this.state.colored is **true**)

### Version

- ant-design-charts: 1.2.2
- Browser: tested on Firefox & Chrome
- Development environment: Windows

**Comment by Shamann** [comment]
@stenterstal, there is a workaround: the desided coloring behavior could be achieved by setting color property of the chart's config to false: <https://codesandbox.io/s/tender-mccarthy-lr0yi?file=/src/App.js>
Please also consider that there is no use in updating the chart (line 66 of App.js in your sandbox) by calling update method without arguments: in that case the chart's options won't be modified at all. You can pass { color: false } to update method in order to implement the workaround described above, but this way will be trickier and a bit confusing, if you leave the rest of the code as is.

**Comment by stenterstal** [comment]
That works, thanks :)
