### ISSUE TITLE
is it possible control legend from my code

### ISSUE THREAD

**Issue by gwmaster** [ant-design/ant-design-charts#794]
how can i get access to legend and turn on/off manually  
for example i want turn all in one click and then select which to show?

**Comment by Shamann** [comment]
SInce chart components of ant-design-charts are ref forwarding components (react components wrapped with forwardRef), you can pass a ref (or a ref callback) to a component and obtain a whole G2 chart object, which allows you to get access to and manipulate all of the chart's components: canvas, axes, tooltip, legend, data, graphical elements and its attributes, etc. To get familiar with this "low-level" operations I highly recommend you to check [G2](https://github.com/antvis/G2)and [G2Plot](https://github.com/antvis/G2Plot) internals and APIs, which compose a foundation ant-design-charts UI library is built upon.
Here is a quick example of how to get access to the chart's legend using ref and control it from the outer component (toggling its visibility and listing its items to console): <https://codesandbox.io/s/jovial-diffie-ztjld?file=/App.tsx>
Maybe someone from the ant-design team would like something to add.

**Comment by gwmaster** [comment]
this good example if you have time can you please help me 
how can i toggle off only "Count" to hide the green line and keep see the blue

**Comment by lxfu1** [comment]
https://codesandbox.io/s/tender-sanderson-c9phqn?file=/index.js
